DECLARE @month TINYINT = 10
DECLARE @year SMALLINT = 2019

;WITH cal(d) AS
(
	SELECT DATEFROMPARTS(@year, @month, 1)
	UNION ALL
	SELECT DATEADD(DAY, 1, d)
	FROM cal
	WHERE d < DATEADD(DAY, -1, DATEADD(MONTH, 1, DATEFROMPARTS(@year, @month, 1)))
)
SELECT 
	SUM(CASE WHEN DATEPART(dw, cte.d) NOT IN (1,7) THEN 1 ELSE 0 END )
FROM cal cte
